<?php

/**
 * @file
 * Contains feed_block.module.
 */

use Drupal\block_content\BlockContentInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function afbiintra_common_block_content_view_alter(array &$build, BlockContentInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->bundle() == 'feed_block') {
    // Default to 1 hour feed cache if not specified and add 'max age' to bubble up expiration via custom event subscriber.
    $build['#cache']['max-age'] = \Drupal::config('feed_block')
      ->get('cache_expiration') ?: 3600;
  }
}
