<?php

/**
 * Implements hook_preprocess_field().
 */
function uregni_theme_preprocess_field(&$variables, $hook) {
  if (isset($variables['element']['#bundle'])) {
    switch ($variables['element']['#bundle']) {
      case 'feed_block':
        if ($variables['element']['#field_name'] == 'field_read_more') {
          // Add 'btn' class to Read more <a> tag.
          $variables['items'][0]['content']['#options']['attributes']['class'][] = 'btn';
        }
        break;
    }
  }
}
