_core:
  default_config_hash: C9_7ISEphRfV6e2q4N7kp5I8GYyxNCP8hKeU2JZxowM
enabled: true
location: /app/log/pbni
rotation:
  schedule: daily
  delete: true
  destination: 'archive/[date:custom:Y/m/d].log'
  gzip: true
format: "[[log:created:custom:'D, d/m/Y - H:i:s.000']] [[log:level]] [[log:channel]] [client: [log:ip], [log:user]] [log:message]"
level: 7
channels_type: exclude
channels: {  }
