_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 21701583-d596-4480-9a3c-2315a9bc7bec
name: 'Public prosecution service intranet'
mail: webdev@webdev-finance.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Public prosecution service intranet'
frontpage_show_title: 0
