#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
name: unity_intranet
proxy:
    appserver:
        - uregni.intranet.nigov.net.lndo.site
        - niaomi.intranet.gov.uk.lndo.site
        - pps.intranet.nigov.net.lndo.site
services:
    uregni_intranet_solr:
        type: 'solr:8.11'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/
    niaomi_intranet_solr:
        type: 'solr:8.11'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/
    pps_intranet_solr:
        type: 'solr:8.11'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/
