#!/usr/bin/env bash
#
# nicsdru-logging/scripts/example.cronjob.sh
#
# Calls shiplog.sh to ship latest log entries from various logs
# to logz.io.

# /bin/bash /app/nicsdru-logging/scripts/shiplog.sh "[LOG_NAME]" "[LOG_PATH]" "[LOG_DATE_PATTERN]" "[LOG_TYPE]"

# Ship /var/log/access.log generated by nginx.
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "access" "/var/log/access.log" "$(date +%d/%b/%Y:)" "nginx_access"

# Uncomment following line to ship drupal.log generated by D9 filelog module.
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-afbiintra" "/app/log/afbiintra/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-niaomiintra" "/app/log/niaomiintra/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-ppsintra" "/app/log/ppsintra/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-pbniintra" "/app/log/pbniintra/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-poniintra" "/app/log/poniintra/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-uregniintra" "/app/log/uregniintra/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"

