#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    unity.svr.3-solr-8983-http:
      entrypoints:
        - http-8983
      rule: HostRegexp(`^solr\.unity\.svr\.3\.ddev\.site$`)|| HostRegexp(`^boundarycommission\.ddev\.site$`)|| HostRegexp(`^horizoneuropeni\.ddev\.site$`)|| HostRegexp(`^independentpaneltruthrecoveryni\.ddev\.site$`)|| HostRegexp(`^industrialcourt\.ddev\.site$`)|| HostRegexp(`^infolibrarynics\.ddev\.site$`)|| HostRegexp(`^interchangeni\.ddev\.site$`)|| HostRegexp(`^judiciaryni\.ddev\.site$`)|| HostRegexp(`^lgbcni\.ddev\.site$`)|| HostRegexp(`^liofa\.ddev\.site$`)|| HostRegexp(`^nibureau\.ddev\.site$`)|| HostRegexp(`^nicscommissioners\.ddev\.site$`)|| HostRegexp(`^pacni\.ddev\.site$`)|| HostRegexp(`^parolecomni\.ddev\.site$`)|| HostRegexp(`^pressclippingsnics\.ddev\.site$`)|| HostRegexp(`^semcommittee\.ddev\.site$`)
      
      service: "unity.svr.3-solr-8983"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "unity.svr.3-redirectHttps"
    unity.svr.3-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^unity\.svr\.3\.ddev\.site$`)|| HostRegexp(`^boundarycommission\.ddev\.site$`)|| HostRegexp(`^horizoneuropeni\.ddev\.site$`)|| HostRegexp(`^independentpaneltruthrecoveryni\.ddev\.site$`)|| HostRegexp(`^industrialcourt\.ddev\.site$`)|| HostRegexp(`^infolibrarynics\.ddev\.site$`)|| HostRegexp(`^interchangeni\.ddev\.site$`)|| HostRegexp(`^judiciaryni\.ddev\.site$`)|| HostRegexp(`^lgbcni\.ddev\.site$`)|| HostRegexp(`^liofa\.ddev\.site$`)|| HostRegexp(`^nibureau\.ddev\.site$`)|| HostRegexp(`^nicscommissioners\.ddev\.site$`)|| HostRegexp(`^pacni\.ddev\.site$`)|| HostRegexp(`^parolecomni\.ddev\.site$`)|| HostRegexp(`^pressclippingsnics\.ddev\.site$`)|| HostRegexp(`^semcommittee\.ddev\.site$`)
      
      service: "unity.svr.3-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "unity.svr.3-redirectHttps"
    unity.svr.3-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^unity\.svr\.3\.ddev\.site$`)|| HostRegexp(`^boundarycommission\.ddev\.site$`)|| HostRegexp(`^horizoneuropeni\.ddev\.site$`)|| HostRegexp(`^independentpaneltruthrecoveryni\.ddev\.site$`)|| HostRegexp(`^industrialcourt\.ddev\.site$`)|| HostRegexp(`^infolibrarynics\.ddev\.site$`)|| HostRegexp(`^interchangeni\.ddev\.site$`)|| HostRegexp(`^judiciaryni\.ddev\.site$`)|| HostRegexp(`^lgbcni\.ddev\.site$`)|| HostRegexp(`^liofa\.ddev\.site$`)|| HostRegexp(`^nibureau\.ddev\.site$`)|| HostRegexp(`^nicscommissioners\.ddev\.site$`)|| HostRegexp(`^pacni\.ddev\.site$`)|| HostRegexp(`^parolecomni\.ddev\.site$`)|| HostRegexp(`^pressclippingsnics\.ddev\.site$`)|| HostRegexp(`^semcommittee\.ddev\.site$`)
      
      service: "unity.svr.3-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "unity.svr.3-redirectHttps"
    
    
    
    
    unity.svr.3-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^unity\.svr\.3\.ddev\.site$`) || HostRegexp(`^boundarycommission\.ddev\.site$`) || HostRegexp(`^horizoneuropeni\.ddev\.site$`) || HostRegexp(`^independentpaneltruthrecoveryni\.ddev\.site$`) || HostRegexp(`^industrialcourt\.ddev\.site$`) || HostRegexp(`^infolibrarynics\.ddev\.site$`) || HostRegexp(`^interchangeni\.ddev\.site$`) || HostRegexp(`^judiciaryni\.ddev\.site$`) || HostRegexp(`^lgbcni\.ddev\.site$`) || HostRegexp(`^liofa\.ddev\.site$`) || HostRegexp(`^nibureau\.ddev\.site$`) || HostRegexp(`^nicscommissioners\.ddev\.site$`) || HostRegexp(`^pacni\.ddev\.site$`) || HostRegexp(`^parolecomni\.ddev\.site$`) || HostRegexp(`^pressclippingsnics\.ddev\.site$`) || HostRegexp(`^semcommittee\.ddev\.site$`)
      
      service: "unity.svr.3-web-80"
      ruleSyntax: v3
      
      tls: true
      
    unity.svr.3-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^unity\.svr\.3\.ddev\.site$`) || HostRegexp(`^boundarycommission\.ddev\.site$`) || HostRegexp(`^horizoneuropeni\.ddev\.site$`) || HostRegexp(`^independentpaneltruthrecoveryni\.ddev\.site$`) || HostRegexp(`^industrialcourt\.ddev\.site$`) || HostRegexp(`^infolibrarynics\.ddev\.site$`) || HostRegexp(`^interchangeni\.ddev\.site$`) || HostRegexp(`^judiciaryni\.ddev\.site$`) || HostRegexp(`^lgbcni\.ddev\.site$`) || HostRegexp(`^liofa\.ddev\.site$`) || HostRegexp(`^nibureau\.ddev\.site$`) || HostRegexp(`^nicscommissioners\.ddev\.site$`) || HostRegexp(`^pacni\.ddev\.site$`) || HostRegexp(`^parolecomni\.ddev\.site$`) || HostRegexp(`^pressclippingsnics\.ddev\.site$`) || HostRegexp(`^semcommittee\.ddev\.site$`)
      
      service: "unity.svr.3-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    unity.svr.3-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    unity.svr.3-solr-8983:
      loadbalancer:
        servers:
          - url: http://ddev-unity.svr.3-solr:8983
        
    unity.svr.3-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-unity.svr.3-web:80
        
    unity.svr.3-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-unity.svr.3-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/unity.svr.3.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/unity.svr.3.key