_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 744ca88a-4d90-45af-8c60-ee844b67db60
name: 'Utility Regulator Intranet'
mail: noreply@email.uregni.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Utility Regulator Intranet'
frontpage_show_title: false
