_core:
  default_config_hash: yOPH6uEZYRHbg2OFP-bze0jGr06fI-Gr_66W-vA8Faw
report-only:
  enable: true
  directives:
    default-src:
      base: self
    connect-src:
      base: self
      sources:
        - 'https://www.google-analytics.com'
        - 'https://region1.google-analytics.com'
        - 'https://*.newrelic.com'
        - 'https://*.nr-data.net'
    font-src:
      base: self
      sources:
        - 'https://themes.googleusercontent.com'
        - 'https://fonts.gstatic.com'
        - 'https://use.fontawesome.com'
        - 'https://cdn.jsdelivr.net'
        - 'data:'
    frame-src:
      base: self
      sources:
        - 'https://www.youtube.com'
        - 'https://www.vimeo.com'
    img-src:
      base: self
      sources:
        - 'https://translate.google.com'
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - 'https://cdn.jsdelivr.net'
        - 'https://i.ytimg.com'
        - 'https://www.gstatic.com'
        - 'https://maps.gstatic.com'
        - 'https://maps.googleapis.com'
        - 'data:'
    manifest-src:
      base: self
    script-src:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - cdn.jsdelivr.net
        - cdnjs.cloudflare.com
        - unpkg.com
        - 'https://*.newrelic.com'
        - 'https://*.nr-data.net'
        - 'https://app.feedblitz.com'
    script-src-attr:
      base: self
      flags:
        - unsafe-hashes
      sources:
        - 'https://app.feedblitz.com'
    script-src-elem:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - cdn.jsdelivr.net
        - cdnjs.cloudflare.com
        - unpkg.com
        - 'https://*.newrelic.com'
        - 'https://*.nr-data.net'
    style-src:
      base: self
      sources:
        - cdn.jsdelivr.net
        - cdnjs.cloudflare.com
        - fonts.googleapis.com
        - unpkg.com
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
      flags:
        - unsafe-inline
    block-all-mixed-content: true
  reporting:
    plugin: none
enforce:
  enable: false
  directives:
    script-src:
      base: self
    script-src-attr:
      base: self
    script-src-elem:
      base: self
    style-src:
      base: self
    style-src-attr:
      base: self
    style-src-elem:
      base: self
    frame-ancestors:
      base: self
  reporting:
    plugin: none
