_core:
  default_config_hash: M7tFjWgaa0JZRYM-U7i4WVRPEnbxAkDbDBSvEkY8r6k
first_day: 0
country:
  default: GB
timezone:
  default: Europe/London
  user:
    configurable: true
    default: 0
    warn: false
