adding:
  backend_config:
    connector_config:
      host: solr
      port: 8983
      core: niaomiintra
removing:
  backend_config:
    connector_config:
      host: niaomiintra_solr.internal
      port: 8080
      core: niaomiintra_index
