menus:
  -
    menu_name: main
    title: Home
    parent: null
    uri: 'internal:/'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: 2b296a9f-beea-47ce-9c77-457f479c7829
  -
    menu_name: main
    title: 'Our office'
    parent: null
    uri: 'entity:node/12'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: und
    uuid: 81a0b5e2-de35-4048-9f72-5e59f21f0c83
  -
    menu_name: main
    title: 'Our purpose and values'
    parent: 'menu_link_content:81a0b5e2-de35-4048-9f72-5e59f21f0c83'
    uri: 'entity:node/19'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: b5e9daae-8293-45e2-9743-c0c564e389e8
  -
    menu_name: main
    title: 'Role of C&AG'
    parent: 'menu_link_content:81a0b5e2-de35-4048-9f72-5e59f21f0c83'
    uri: 'entity:node/20'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: f933996d-cdeb-4845-a01a-5e2089d2273d
  -
    menu_name: main
    title: Contacts
    parent: null
    uri: 'entity:node/23'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 50
    langcode: und
    uuid: fb4c50e5-2515-439f-ba25-525f5bb8a180
  -
    menu_name: main
    title: 'Senior management'
    parent: 'menu_link_content:81a0b5e2-de35-4048-9f72-5e59f21f0c83'
    uri: 'entity:node/424'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 4
    langcode: und
    uuid: 797eefbc-db78-4166-b08d-5d59a8aaf927
  -
    menu_name: main
    title: 'Team brief'
    parent: 'menu_link_content:81a0b5e2-de35-4048-9f72-5e59f21f0c83'
    uri: 'entity:node/427'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 7
    langcode: und
    uuid: 605b13db-55f8-4507-a8b2-31df188c3014
  -
    menu_name: main
    title: 'Corporate Info & Resources'
    parent: null
    uri: 'entity:node/430'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 6
    langcode: und
    uuid: 6cf394ce-da94-4051-9b2b-15cd565990de
  -
    menu_name: main
    title: 'What we do'
    parent: 'menu_link_content:81a0b5e2-de35-4048-9f72-5e59f21f0c83'
    uri: 'entity:node/532'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: 26f23da8-9bb9-4b2f-b0d7-ba7b30812453
  -
    menu_name: main
    title: 'Central Government Financial Audit'
    parent: 'menu_link_content:26f23da8-9bb9-4b2f-b0d7-ba7b30812453'
    uri: 'entity:node/529'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: d724d4a9-ab9c-47b5-86c6-ed7c5a465be5
  -
    menu_name: main
    title: 'Local Government Financial Audit'
    parent: 'menu_link_content:26f23da8-9bb9-4b2f-b0d7-ba7b30812453'
    uri: 'entity:node/535'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: 682e7ff2-12dc-4dce-b307-d211a823a73f
  -
    menu_name: main
    title: 'Public Reporting work'
    parent: 'menu_link_content:26f23da8-9bb9-4b2f-b0d7-ba7b30812453'
    uri: 'entity:node/538'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: 4f2551c7-e394-4744-926f-d15960a60ff7
  -
    menu_name: main
    title: 'Corporate Services'
    parent: 'menu_link_content:26f23da8-9bb9-4b2f-b0d7-ba7b30812453'
    uri: 'entity:node/540'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 4
    langcode: und
    uuid: e1b5f194-3c30-4259-841f-0adba3c62d4b
  -
    menu_name: main
    title: 'Organisation Chart'
    parent: 'menu_link_content:81a0b5e2-de35-4048-9f72-5e59f21f0c83'
    uri: 'entity:node/607'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 5
    langcode: und
    uuid: c652dc34-9219-4d53-b77f-97e2f27a8a7b
  -
    menu_name: main
    title: 'Additional Information'
    parent: 'menu_link_content:13a4803f-6615-487b-a0fe-f450c31bb643'
    uri: 'http://niaomi.intranet.nigov.net/additional-information'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -1
    langcode: und
    uuid: d29829d9-5e5c-409d-adef-e2277000ebe0
  -
    menu_name: main
    title: "What's On"
    parent: null
    uri: 'http://niaomi.intranet.nigov.net/node/63497'
    link_title: null
    description: 'On this page you will find a list of upcoming reports/eventsOn this page you will find a list of upcoming reports/events'
    enabled: false
    expanded: false
    weight: 0
    langcode: und
    uuid: 98b342cb-2e49-4ddf-864c-e0fead43a786
  -
    menu_name: main
    title: 'Bradford Court'
    parent: 'menu_link_content:6042e979-b4aa-4a1f-baa7-5f12946c419b'
    uri: 'http://niaomi.intranet.nigov.net/decant'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -1
    langcode: und
    uuid: 13a4803f-6615-487b-a0fe-f450c31bb643
  -
    menu_name: main
    title: 'Future Working'
    parent: null
    uri: 'http://niaomi.intranet.nigov.net/future-working'
    link_title: null
    description: null
    enabled: false
    expanded: true
    weight: 0
    langcode: und
    uuid: 6042e979-b4aa-4a1f-baa7-5f12946c419b
  -
    menu_name: main
    title: 'Future Working Group'
    parent: 'menu_link_content:6042e979-b4aa-4a1f-baa7-5f12946c419b'
    uri: 'http://niaomi.intranet.nigov.net/future-working-group'
    link_title: null
    description: null
    enabled: true
    expanded: true
    weight: -1
    langcode: und
    uuid: 37f6fc6b-4f01-43fb-92ad-dfbe772d04d9
  -
    menu_name: main
    title: 'University Street Updates'
    parent: 'menu_link_content:6042e979-b4aa-4a1f-baa7-5f12946c419b'
    uri: 'http://niaomi.intranet.nigov.net/university-street-updates'
    link_title: null
    description: null
    enabled: true
    expanded: true
    weight: -1
    langcode: und
    uuid: c6a93e9e-b491-498f-9da7-175f6eae7968
  -
    menu_name: main
    title: 'Events Calendar'
    parent: null
    uri: 'internal:/events-calendar-24-25'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: 7122ec72-e5c3-4d08-b265-74372a4ebe5e
