adding:
  dependencies:
    config:
      - search_api_solr.solr_field_type.text_string_und_6_0_0
  backend_config:
    connector_config:
      host: solr
      port: 8983
      core: nipbintra
      skip_schema_check: true
      solr_install_dir: /opt/solr
      checkpoints_collection: ''
      stats_cache: org.apache.solr.search.stats.LRUStatsCache
      distrib: true
      context: solr
      username: solr
      password: solr
    index_empty_text_fields: false
    suppress_missing_languages: false
removing:
  backend_config:
    connector_config:
      host: nipbintra_solr.internal
      port: 8080
      core: nipbintra_index
      skip_schema_check: false
      solr_install_dir: ''
