project_type: unity
project_name: 'Unity Intranet'
project_id: 6gl4nbwlja4u4
project_disk_size: 36864
db_disk_size: 12288
sites:
    ppsintra:
        name: 'Public Prosecution Service Northern Ireland'
        url: pps.intranet.nipublicsector.net
        solr: ppsintra
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/ppsintra ; drush core-cron'
        database: ppsintra
        status: development
        default: false
    uregniintra:
        name: 'Utility Regulator Northern Ireland'
        url: uregni.intranet.nipublicsector.net
        solr: uregniintra
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/uregniintra ; drush core-cron'
        database: uregniintra
        status: development
        default: false
    pbniintra:
        name: 'Probation Board Northern Ireland'
        url: pbni.intranet.nipublicsector.net
        solr: pbniintra
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/pbniintra ; drush core-cron'
        database: pbniintra
        status: development
        default: false
    niaomiintra:
        name: 'Northern Ireland Audit Office'
        url: niaomi.intranet.nipublicsector.net
        solr: niaomiintra
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/niaomiintra ; drush core-cron'
        database: niaomiintra
        status: development
        default: false
    nipbintra:
        name: 'Northern Ireland Policing Board Intranet'
        url: nipb.intranet.nipublicsector.net
        solr: nipbintra
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/nipbintra ; drush core-cron'
        database: nipbintra
        status: development
        default: false
    afbiintra:
        name: 'Agri-Foods & Biosciences Institute'
        url: afbi.intranet.nipublicsector.net
        solr: afbiintra
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/afbiintra ; drush core-cron'
        database: afbiintra
        status: development
        default: false
    poniintra:
        name: 'Northern Ireland Police Ombudsman'
        url: poni.intranet.nipublicsector.net
        solr: poniintra
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/poniintra ; drush core-cron'
        database: poniintra
        status: development
        default: true
    nipsintra:
        name: 'Northern Ireland Prison Service'
        url: nips.intranet.nipublicsector.net
        solr: nipsintra
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/nipsintra ; drush core-cron'
        database: nipsintra
        status: development
        default: false
