project_type: unity
project_name: 'Unity Intranet'
project_id: 6gl4nbwlja4u4
project_disk_size: 51200
db_disk_size: 22000
sites:
    niaomi:
        name: NIAO
        url: niaomi.intranet.nigov.net
        solr: niaomi
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/niaomi ; drush core-cron'
        database: niaomi
        status: development
    afbi:
        name: AFBI
        url: afbi.intranet.nigov.net
        solr: afbi
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/afbi ; drush core-cron'
        database: afbi
        default: true
    nipb:
        name: 'NI Policing Board Intranet'
        url: nipb.intranet.nigov.net
        solr: nipb
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/nipb ; drush core-cron'
        database: nipb
        status: development
        default: false
    ppsintra:
        name: PPS
        url: pps.intranet.nigov.net
        solr: ppsintra
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/ppsintra ; drush core-cron'
        database: ppsintra
        status: development
        default: false
    uregniintra:
        name: Uregni
        url: uregni.intranet.nigov.net
        solr: uregniintra
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/uregniintra ; drush core-cron'
        database: uregniintra
        status: development
        default: false
    pbniintra:
        name: PBNI
        url: pbni.intranet.nigov.net
        solr: pbniintra
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/pbniintra ; drush core-cron'
        database: pbniintra
        status: development
        default: false
