project_type: unity
project_name: 'Unity Intranet'
project_id: xxxxxxxxx
project_disk_size: 51200
db_disk_size: 22000
sites:
    uregni:
        name: Uregni
        url: uregni.intranet.nigov.net
        solr: uregni
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/uregni ; drush core-cron'
        database: uregni
        status: development
        default: false
    niaomi:
        name: NIAO
        url: niaomi.intranet.gov.uk
        solr: niaomi
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/niaomi ; drush core-cron'
        database: niaomi
        status: development
        default: false
