project_type: unity
project_name: 'Unity Intranet'
project_id: 6gl4nbwlja4u4
project_disk_size: 51200
db_disk_size: 22000
sites:
    pps:
        name: PPS
        url: pps.intranet.nigov.net
        solr: pps
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/pps ; drush core-cron'
        database: pps
        status: development
        default: false
    niaomi:
        name: NIAO
        url: niaomi.intranet.nigov.net
        solr: niaomi
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/niaomi ; drush core-cron'
        database: niaomi
        status: development
    afbi:
        name: AFBI
        url: afbi.intranet.nigov.net
        solr: afbi
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/afbi ; drush core-cron'
        database: afbi
        default: true
    pbniintranet:
        name: 'PBNI Intranet'
        url: pbni.intranet.nigov.net
        solr: pbni
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/pbni ; drush core-cron'
        database: pbni
        status: development
        default: false
    nipb:
        name: 'NI Policing Board Intranet'
        url: nipb.intranet.nigov.net
        solr: nipb
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/nipb ; drush core-cron'
        database: nipb
        status: development
        default: false
    uregniintranet:
        name: 'Uregni Intranet'
        url: uregni.intranet.nigov.net
        www: false
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/uregnintranet ; drush core-cron'
        database: uregnintranet
        status: development
        default: false
