<?php

/**
 * @file
 * Primary module hooks for Nisra common module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function poni_common_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_object->getEntity();

  if ($node->bundle() === 'publication') {
    $form['#validate'][] = 'poni_common_validate_attachment';
  }
}

/**
 * Form validation callback.
 */
function poni_common_validate_attachment(&$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();

  // Validate file attachments and external links.
  if (empty($values['field_attachment']["selection"][0]) && empty($values['field_external_publication'][0]['uri']) && $values['field_content_manager_link'][0]['url'] === '') {
    $message = t('You must provide an attachment or external link or a content manager link');
    $form_state->setErrorByName('field_content_manager_link', $message);
    $form_state->setErrorByName('field_attachment', $message);
    $form_state->setErrorByName('field_external_publication', $message);
  }
}

