<?php

/**
 * @file
 * Primary module hooks for Nisra common module.
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StreamWrapper\StreamWrapperManager;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\views\Plugin\views\cache\CachePluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function poni_common_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_object->getEntity();

  if ($node->bundle() === 'publication') {
    $form['#validate'][] = 'poni_common_validate_attachment';
  }
}

/**
 * Form validation callback.
 */
function poni_common_validate_attachment(&$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();

  // Validate file attachments and external links.
  if (empty($values['field_attachment']["selection"][0]) && empty($values['field_external_publication'][0]['uri']) && empty($values['field_content_manager_link'][0]['value'])) {
    $message = t('You must provide an attachment or external link or a content manager link');
    $form_state->setErrorByName('field_content_manager_link', $message);
    $form_state->setErrorByName('field_attachment', $message);
    $form_state->setErrorByName('field_external_publication', $message);
  }

  $link_url = $values['field_content_manager_link'][0]['value'];
  $link_text = $values['field_content_manager_link_text'][0]['value'];

  if ($link_url && !preg_match('/^contentmanager:\/\/.*/', $link_url)) {
    $form_state->setErrorByName('field_content_manager_link', 'This link must begin with contentmanager://');
  }

  if ($link_url && empty($link_text)) {
    $form_state->setErrorByName('field_content_manager_link_text', 'You must enter link text for the content manager link.');
  }
}

/**
 * Implements hook_preprocess_HOOK() for fieldset.
 */
function poni_common_preprocess_fieldset(&$variables) {
  $element = &$variables['element'];
  if ($element['#id'] == 'group-publications') {
    $variables['legend_span']['attributes']['class'][] = 'js-form-required form-required';
  }
}
