<?php

/**
 * Implements hook_preprocess_field().
 */
function afbi_theme_preprocess_field(&$variables) {

  if (isset($variables['element']) && $variables['element']['#field_name'] === 'field_external_url') {
    foreach ($variables['items'] as $key => $item) {
      $classes = ['file-link file--ico file--ico__ext'];
      $item['content']['#url']->setOption('attributes', ['class' => $classes]);
    }
  }

  if ($node = \Drupal::request()->attributes->get('node')) {
    $variables['nid'] = $node->id();
  }
}

