<?php

/**
 * Implements hook_preprocess_field().
 */
function poniintra_theme_preprocess_field(&$variables) {

  if (isset($variables['element']) && $variables['element']['#field_name'] === 'field_external_publication') {
    foreach ($variables['items'] as $key => $item) {
      $classes = ['file-link file--ico file--ico__html'];
      $item['content']['#url']->setOption('attributes', ['class' => $classes]);
    }
  }
}
