#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
'https://pps.intranet.nigov.net/':
    type: upstream
    upstream: 'unity_intranet:http'
    cache:
        enabled: 'false'
'https://uregni.intranet.nigov.net/':
    type: upstream
    upstream: 'unity_intranet:http'
    cache:
        enabled: 'false'
'https://pbni.intranet.nigov.net/':
    type: upstream
    upstream: 'unity_intranet:http'
    cache:
        enabled: 'false'
'https://niaomi.intranet.nigov.net/':
    type: upstream
    upstream: 'unity_intranet:http'
    cache:
        enabled: 'false'
'https://nipb.intranet.nigov.net/':
    type: upstream
    upstream: 'unity_intranet:http'
    cache:
        enabled: 'false'
'https://afbiintra.intranet.nigov.net/':
    type: upstream
    upstream: 'unity_intranet:http'
    cache:
        enabled: 'false'
'https://www.{all}/':
    type: upstream
    upstream: 'unity_intranet:http'
    cache:
        enabled: 'false'
'https://{all}/':
    type: redirect
    to: 'https://www.{all}/'
