_core:
  default_config_hash: xmYJY_pX20CqAS5_4LH3yaC8_kA8iG7i4q4zW3zwp9c
enable_form_descriptions: 1
enable_revisions_warning: 0
revisions_warning_caution_limit: ''
revisions_warning_lockdown_limit: ''
revisions_warning_excluded: ''
