# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "phantomjs"

snap_file: javascript/snap.js

# (required) The domains to take screenshots of.
domains:
  current:  "https://www.pcsps.org/"
  new:      "https://www.pcsps.org.uat-nvcvooy-6tlkpwbr6tndk.uk-1.platformsh.site/"

# (required) The paths to capture. All paths should exist for both of the domains specified above.
paths:
  home:     /
  pcsp-projects-coming-life:    /pcsp-projects-coming-life
  recruitment:     /recruitment
  contact-us:  /contact-us
  publication: /publications/code-practice-appointment-independent-members-pcsps-and-dpcsps-2023
  projects: /pcsp-projects-coming-life

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  - 1200x3000

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: 'javascript/wait--phantom.js'

# (required) The directory that your screenshots will be stored in
directory: 'shots/pcsps'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 2

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  template: 'slideshow_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first

# (optional) Set the number of threads to use when saving images. Raising this value can improve performance, but very high
# values can lead to server connection issues. Set to around 1.5 the available CPU cores for best performance. Default: 8
threads: 8
