adding:
  backend_config:
    connector_config:
      host: solr
      core: ppsintra
      skip_schema_check: true
      solr_install_dir: /opt/solr
      checkpoints_collection: ''
      stats_cache: org.apache.solr.search.stats.LRUStatsCache
      distrib: true
      context: solr
      username: solr
      password: SolrRocks
removing:
  backend_config:
    connector_config:
      host: ppsintra_solr.internal
      core: ppsintra_index
      skip_schema_check: false
      solr_install_dir: ''
