_core:
  default_config_hash: 6SRqhVdje-gEz9pzyMu3GhH-kMazpJ5CUm2GbngChdA
langcode: en
uuid: fff7f46f-347d-4f21-ba80-6bbba3b04125
name: 'NI Policing Board Intranet'
mail: test@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to NI Policing Board site'
frontpage_show_title: 0
