_core:
  default_config_hash: _SJP1brENn3JDFFDwwMZ2cK54qh632xDdVRUfN98RZ0
interface:
  default: php_mail
  webform: webform_php_mail
mailer_dsn:
  scheme: sendmail
  host: default
  user: null
  password: null
  port: null
  options: {  }
