services:
  ddev-router:
    image: ddev/ddev-traefik-router:v1.23.4

    
    # Prevent zombie container
    init: true
    command:
      - --configFile=/mnt/ddev-global-cache/traefik/.static_config.yaml
    user: 501:20
    

    networks:
      - ddev_default
    container_name: ddev-router
    ports: 
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
      - "127.0.0.1:8025:8025"
      - "127.0.0.1:8026:8026"
      - "127.0.0.1:8983:8983"
      
      # Traefik router; configured in static config as entrypoint
      - "127.0.0.1:10999:10999"
      
    labels:
      # For cleanup on ddev poweroff
      com.ddev.site-name: ""
    volumes:
      
      - ddev-global-cache:/mnt/ddev-global-cache:rw
       
    environment:
      - TRAEFIK_MONITOR_PORT=10999
      - DISABLE_HTTP2=false
        
    restart: "no"
    healthcheck:
      
      test: "/healthcheck.sh"
      
      interval: 1s
      retries: 120
      start_period: 120s
      timeout: 120s

networks:
  ddev_default:
    name: ddev_default
    external: true
volumes:
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  
