name: ddev-unitysvr3
services:
  ddev-router:
    command:
      - --configFile=/mnt/ddev-global-cache/traefik/.static_config.yaml
    container_name: ddev-router
    environment:
      DISABLE_HTTP2: "false"
      TRAEFIK_MONITOR_PORT: "10999"
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
      timeout: 2m0s
      interval: 1s
      retries: 120
      start_period: 2m0s
    image: ddev/ddev-traefik-router:v1.23.4
    init: true
    labels:
      com.ddev.site-name: ""
    networks:
      ddev_default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 443
        published: "443"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 80
        published: "80"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8025
        published: "8025"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8026
        published: "8026"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8983
        published: "8983"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 10999
        published: "10999"
        protocol: tcp
    restart: "no"
    user: "501:20"
    volumes:
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
networks:
  ddev_default:
    name: ddev_default
    external: true
volumes:
  ddev-global-cache:
    name: ddev-global-cache
    external: true
