#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
name: unity.intranet
additional_hostnames:
    - pps
    - niaomi
    - afbi
    - pbni
    - nipb
    - uregniintranet
